### ISSUE TITLE
Linked items causing some issues with properties and initialising.

### ISSUE THREAD

**Issue by jdudetv** [Brendonovich/simple-obs#18] opened 2021-09-24 23:29 UTC
Going to test more to see where the issue is. Currently happening on webcam linked scene when running the window function its not picking up the bounds item and assigning it to content on the window.

**Comment by jdudetv** [comment] 2021-09-25 00:38
So linking isnt getting the properties of items correctly. they initialise but they don't populate the object with their properties.

`{
    "position": {
        "x": 960,
        "y": 540,
        "alignment": 0
    },
    "scale": {
        "x": 0.5,
        "y": 0.5,
        "filter": ""
    },
    "crop": {
        "top": 0,
        "right": 0,
        "bottom": 0,
        "left": 0
    },
    "bounds": {
        "type": "",
        "alignment": 0,
        "x": 0,
        "y": 0
    },
    "rotation": 0,
    "visible": true,
    "locked": false,
    "sourceWidth": 0,
    "sourceHeight": 0,
    "width": 0,
    "height": 0
}`

**Comment by jdudetv** [comment] 2021-09-25 00:44
`  await Promise.all([cameraScene.link(), greenScreenCameraScene.link()]);

  console.log(cameraScene);`
  
  So running a console log directly after linking is called.
  
  the linked property on camera scene is saying false.
  
  `linked: false`

**Comment by Brendonovich** [comment] 2021-10-03 09:29
Seems to have been caused by #22, should be fixed when not using batching.

**Closed by Brendonovich** 2021-10-03 09:29 UTC
Labels: bug
